#!/bin/bash

# Update package list and install git and figlet
if command -v apt-get &>/dev/null; then
    sudo apt update && sudo apt install git figlet -y
elif command -v yum &>/dev/null; then
    sudo yum install git figlet -y
elif command -v dnf &>/dev/null; then
    sudo dnf install git figlet -y
elif command -v pacman &>/dev/null; then
    sudo pacman -S git figlet --noconfirm
else
    echo "Unsupported package manager. Exiting."
    exit 1
fi

# Clone the repository
sudo git clone https://github.com/farooq-001/emil.git

# Change file permissions
sudo chmod 644 /home/snb-tech/.iplist.txt

# Run the Python script
sudo python3 emil/ip.py

# Clean up by removing the cloned repository
sudo rm -rf emil

# Print the welcome message using figlet
figlet -f digital -c "Hi Mr Welcome to Cyberworld"
